# Modelo machine learning - Itaú 

**Algoritmos:** Random florest, naive bayes

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
import pandas.util.testing as tm

C:\Users\RafaelHenriqueGallo\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:8: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  


In [44]:
dados = pd.read_csv("Dados\ITUB4.SA.csv")

In [45]:
dados.head()

Date       Open       High        Low      Close  Adj Close  \
0  2011-01-03  18.031601  18.250099  17.963200  18.068001  12.447648   
1  2011-01-04  18.077101  18.318399  18.031601  18.213699  12.548030   
2  2011-01-05  18.122601  18.509701  18.004200  18.486900  12.736247   
3  2011-01-06  18.400400  18.436800  18.031601  18.049801  12.435113   
4  2011-01-07  18.013300  18.149900  17.512501  17.608101  12.130811   

       Volume  
0  10014664.0  
1  12685182.0  
2  12143831.0  
3  17066721.0  
4  15259729.0

In [46]:
dados.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')

In [47]:
dados.columns = ["Data", "Aberta", "Alta", "Baixa", "Fechada", "Adj fechada", "Volume"]
dados

Data     Aberta       Alta      Baixa    Fechada  Adj fechada  \
0     2011-01-03  18.031601  18.250099  17.963200  18.068001    12.447648   
1     2011-01-04  18.077101  18.318399  18.031601  18.213699    12.548030   
2     2011-01-05  18.122601  18.509701  18.004200  18.486900    12.736247   
3     2011-01-06  18.400400  18.436800  18.031601  18.049801    12.435113   
4     2011-01-07  18.013300  18.149900  17.512501  17.608101    12.130811   
...          ...        ...        ...        ...        ...          ...   
2361  2020-07-08  26.650000  27.070000  26.500000  26.940001    26.940001   
2362  2020-07-09  27.020000  27.170000  26.580000  26.950001    26.950001   
2363  2020-07-10  26.950001  27.309999  26.620001  27.200001    27.200001   
2364  2020-07-13  27.450001  27.549999  26.799999  26.799999    26.799999   
2365  2020-07-14   0.000000   0.000000   0.000000  27.250000    27.250000   

          Volume  
0     10014664.0  
1     12685182.0  
2     12143831.0  
3     17066721.0  
4     15259729.0  
...          ...  
2361  33988600.0  
2362  43480000.0  
2363  24056400.0  
2364  24781700.0  
2365         0.0  

[2366 rows x 7 columns]

In [48]:
dados.drop("Data", inplace = True, axis = 1)
dados

Aberta       Alta      Baixa    Fechada  Adj fechada      Volume
0     18.031601  18.250099  17.963200  18.068001    12.447648  10014664.0
1     18.077101  18.318399  18.031601  18.213699    12.548030  12685182.0
2     18.122601  18.509701  18.004200  18.486900    12.736247  12143831.0
3     18.400400  18.436800  18.031601  18.049801    12.435113  17066721.0
4     18.013300  18.149900  17.512501  17.608101    12.130811  15259729.0
...         ...        ...        ...        ...          ...         ...
2361  26.650000  27.070000  26.500000  26.940001    26.940001  33988600.0
2362  27.020000  27.170000  26.580000  26.950001    26.950001  43480000.0
2363  26.950001  27.309999  26.620001  27.200001    27.200001  24056400.0
2364  27.450001  27.549999  26.799999  26.799999    26.799999  24781700.0
2365   0.000000   0.000000   0.000000  27.250000    27.250000         0.0

[2366 rows x 6 columns]

In [49]:
dados.drop(["Adj fechada"], axis = 1, inplace=True)
dados.dropna(inplace=True)
dados

Aberta       Alta      Baixa    Fechada      Volume
0     18.031601  18.250099  17.963200  18.068001  10014664.0
1     18.077101  18.318399  18.031601  18.213699  12685182.0
2     18.122601  18.509701  18.004200  18.486900  12143831.0
3     18.400400  18.436800  18.031601  18.049801  17066721.0
4     18.013300  18.149900  17.512501  17.608101  15259729.0
...         ...        ...        ...        ...         ...
2361  26.650000  27.070000  26.500000  26.940001  33988600.0
2362  27.020000  27.170000  26.580000  26.950001  43480000.0
2363  26.950001  27.309999  26.620001  27.200001  24056400.0
2364  27.450001  27.549999  26.799999  26.799999  24781700.0
2365   0.000000   0.000000   0.000000  27.250000         0.0

[2352 rows x 5 columns]

In [50]:
dados.describe()

Aberta         Alta        Baixa      Fechada        Volume
count  2352.000000  2352.000000  2352.000000  2352.000000  2.352000e+03
mean     22.072680    22.346019    21.780293    22.077967  2.162460e+07
std       7.416312     7.485330     7.331993     7.394056  1.125248e+07
min       0.000000     0.000000     0.000000    11.634000  0.000000e+00
25%      15.981375    16.191999    15.786700    15.991600  1.447485e+07
50%      19.283701    19.606051    19.038850    19.333600  1.934621e+07
75%      27.721674    28.045001    27.367525    27.706676  2.557753e+07
max      38.669998    39.790001    38.400002    39.689999  1.049172e+08

In [51]:
x1 = dados.iloc[:,0:4].values
x2 = dados.iloc[:,4].values

x1

array([[18.031601, 18.250099, 17.9632  , 18.068001],
       [18.077101, 18.318399, 18.031601, 18.213699],
       [18.122601, 18.509701, 18.0042  , 18.4869  ],
       ...,
       [26.950001, 27.309999, 26.620001, 27.200001],
       [27.450001, 27.549999, 26.799999, 26.799999],
       [ 0.      ,  0.      ,  0.      , 27.25    ]])

In [52]:
x2

array([10014664., 12685182., 12143831., ..., 24056400., 24781700.,
              0.])

In [53]:
dados1 = dados.sort_values("Volume", ascending=True)

x_dados1 = dados1[["Alta", "Baixa", "Fechada"]]
x_dados2 = dados1["Volume"]
dados1.head()

Aberta     Alta    Baixa  Fechada  Volume
2365   0.0000   0.0000   0.0000  27.2500     0.0
1738  28.3867  28.3867  28.3867  28.3867     0.0
1734  28.3533  28.3533  28.3533  28.3533     0.0
404   15.4589  15.4589  15.4589  15.4589     0.0
1709  28.3533  28.3533  28.3533  28.3533     0.0

In [54]:
from sklearn.model_selection import train_test_split

x = dados[["Aberta", "Alta", "Baixa", "Fechada", "Volume"]]
y = dados["Volume"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3)

In [55]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler1 = scaler.fit_transform(dados)
scaler1

array([[-0.54500647, -0.54730927, -0.52071851, -0.54243826, -1.0319864 ],
       [-0.53887004, -0.53818282, -0.51138741, -0.52272932, -0.79460883],
       [-0.53273361, -0.51262046, -0.51512539, -0.48577274, -0.84272855],
       ...,
       [ 0.65778765,  0.66330217,  0.66022129,  0.6928704 ,  0.21615843],
       [ 0.72522094,  0.6953717 ,  0.68477618,  0.63876112,  0.28062905],
       [-2.97686684, -2.98594311, -2.97121469,  0.69963389, -1.92217199]])

In [56]:
from sklearn import preprocessing

min_max_scaler = preprocessing.MinMaxScaler()
d1 = preprocessing.MinMaxScaler()
d2 = min_max_scaler.fit_transform(dados)
n2_r = min_max_scaler.inverse_transform(dados)

print("Max", d2)
print("\n")
print("Inverse", n2_r)

Max [[0.46629433 0.45866043 0.46779164 0.2293271  0.09545302]
 [0.46747096 0.46037694 0.46957292 0.23452022 0.1209066 ]
 [0.46864758 0.46518473 0.46885935 0.24425792 0.11574681]
 ...
 [0.69692274 0.68635331 0.69322916 0.55481899 0.22928938]
 [0.70985266 0.69238498 0.6979166  0.54056172 0.23620245]
 [0.         0.         0.         0.5566011  0.        ]]


Inverse [[6.97281975e+02 7.26171457e+02 6.89786916e+02 5.18549818e+02
  1.05071051e+15]
 [6.99041460e+02 7.28889115e+02 6.92413514e+02 5.22637521e+02
  1.33089378e+15]
 [7.00800944e+02 7.36501021e+02 6.91361316e+02 5.30302448e+02
  1.27409675e+15]
 ...
 [1.04215648e+03 1.08666489e+03 1.02220809e+03 7.74757201e+02
  2.52393013e+15]
 [1.06149148e+03 1.09621449e+03 1.02912002e+03 7.63534745e+02
  2.60002658e+15]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 7.76159973e+02
  0.00000000e+00]]


**Naive bayes**

In [57]:
from sklearn.preprocessing import LabelEncoder

labelencoder = LabelEncoder()
x1[:,0] = labelencoder.fit_transform(x1[:,0])
x1[:,1] = labelencoder.fit_transform(x1[:,1])
x1[:,2] = labelencoder.fit_transform(x1[:,2])
x1[:,3] = labelencoder.fit_transform(x1[:,3])
x1[:,0]

array([ 742.,  745.,  748., ..., 1323., 1344.,    0.])

In [58]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()
gnb.fit(x_train, y_train)
y_pred = gnb.predict(x_test)
y_pred

array([1.0078050e+07, 1.9148890e+07, 1.0132700e+07, 1.6033050e+07,
       2.0000574e+07, 1.3318112e+07, 2.8766430e+07, 2.9822718e+07,
       1.3523746e+07, 5.9262000e+06, 2.0285178e+07, 1.0075497e+07,
       3.4659240e+07, 1.9343689e+07, 3.0374025e+07, 2.2786962e+07,
       2.2660075e+07, 1.3823446e+07, 9.6241880e+06, 1.5570750e+07,
       2.3790600e+07, 5.7810700e+07, 3.1030200e+07, 1.4343000e+07,
       1.9522200e+07, 4.7479600e+07, 1.1616235e+07, 2.0523294e+07,
       1.6650900e+07, 2.5124220e+07, 3.5539350e+07, 1.5032700e+07,
       9.3072000e+06, 5.2808250e+06, 2.3083293e+07, 2.6625523e+07,
       2.6389138e+07, 8.3661000e+06, 5.9605500e+07, 1.2123900e+07,
       1.7878113e+07, 2.1901106e+07, 1.8964753e+07, 3.2900200e+07,
       1.1616235e+07, 1.3957851e+07, 4.4550000e+04, 0.0000000e+00,
       2.3278900e+07, 1.8248010e+07, 2.8766430e+07, 3.4659240e+07,
       1.7764258e+07, 1.3426462e+07, 2.5543620e+07, 2.1134100e+07,
       1.2559382e+07, 2.2434060e+07, 2.0492010e+07, 7.3678630e

**Random Forest**

**Avore - 1**

In [60]:
from sklearn.ensemble import RandomForestClassifier

avore1 = RandomForestClassifier(n_estimators = 100)
avore1.fit(x_train, y_train)
X1 = avore1.predict(x_test)
X1

array([9.5386500e+06, 1.8130316e+07, 1.0362000e+07, 1.6683932e+07,
       1.9756346e+07, 2.0161300e+07, 2.8733628e+07, 3.0355875e+07,
       1.8438900e+07, 7.5670500e+06, 1.9366600e+07, 1.0426200e+07,
       3.1219089e+07, 1.8313475e+07, 3.0489300e+07, 1.3641000e+07,
       2.2929258e+07, 1.3777800e+07, 1.0364071e+07, 1.6119521e+07,
       3.5605301e+07, 5.3968500e+07, 2.3599455e+07, 1.4905050e+07,
       1.8934606e+07, 4.6544223e+07, 1.0612849e+07, 2.3172930e+07,
       1.4219799e+07, 2.0561700e+07, 1.8612400e+07, 2.9178900e+07,
       9.7271880e+06, 6.1831500e+06, 2.0071400e+07, 2.3916000e+07,
       2.0832899e+07, 9.8736000e+06, 5.7364300e+07, 1.1894850e+07,
       1.7621249e+07, 2.2982025e+07, 1.8669400e+07, 3.0844700e+07,
       1.1810400e+07, 1.3880766e+07, 2.7225000e+05, 0.0000000e+00,
       2.2524000e+07, 2.1962697e+07, 2.4741800e+07, 3.3409200e+07,
       1.3221750e+07, 2.2352854e+07, 2.6176400e+07, 2.5707841e+07,
       1.4733092e+07, 2.2720533e+07, 2.0597250e+07, 1.0170600e

**Avore - 2**

In [61]:
avore2 = RandomForestClassifier(n_estimators = 40, criterion='entropy', random_state=0)
avore2.fit(x_train, y_train)
x2 = avore2.predict(x_test)
x2

array([9.5386500e+06, 1.8733379e+07, 1.0241400e+07, 1.6312563e+07,
       1.9756346e+07, 1.6447900e+07, 2.8733628e+07, 3.0355875e+07,
       1.2597150e+07, 7.5670500e+06, 1.9366600e+07, 1.0426200e+07,
       3.1219089e+07, 1.8313475e+07, 3.0489300e+07, 2.2785450e+07,
       2.2929258e+07, 1.3777800e+07, 1.0364071e+07, 1.6119521e+07,
       2.3804948e+07, 4.3889700e+07, 2.8772832e+07, 1.4409450e+07,
       1.9284045e+07, 4.7338830e+07, 1.0612849e+07, 2.0277015e+07,
       1.6305778e+07, 2.1112200e+07, 3.2900200e+07, 1.4932500e+07,
       9.9479010e+06, 6.1831500e+06, 2.0071400e+07, 2.3916000e+07,
       3.0407454e+07, 1.1988075e+07, 5.7364300e+07, 1.1538100e+07,
       1.7621249e+07, 2.2982025e+07, 1.8669400e+07, 3.0844700e+07,
       1.1810400e+07, 1.3880766e+07, 1.3523746e+07, 0.0000000e+00,
       2.2524000e+07, 1.8434044e+07, 2.6851200e+07, 4.0709790e+07,
       1.4962650e+07, 1.3517962e+07, 2.2857500e+07, 2.1184498e+07,
       1.0315975e+07, 2.2720533e+07, 2.0597250e+07, 1.0170600e